include: package:flint/analysis_options.dart.dev.yaml
# include: package:lint/analysis_options.yaml


linter:
  rules:
    always_declare_return_typescd
    prefer_const_constructors
    unused_local_variable
