name: Flutter_CI

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    - name: sets up a Flutter environment for use in actions.
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.1.x'
    
    - name: Getting the dependencies for the Flutter project.
        run: flutter pub get
          working-directory: ./hortum_mobile
    
    - name: Run tests for Flutter.
        run: flutter test
          working-directory: ./hortum_mobile