List<Map> categories = [
  {'name': 'Artesanato', 'image_path': 'assets/images/artesanato.jpg'},
  {'name': 'Açúcar', 'image_path': 'assets/images/acucar.jpg'},
  {'name': 'Bebidas', 'image_path': 'assets/images/bebidas.jpeg'},
  {'name': 'Café', 'image_path': 'assets/images/cafe.jpeg'},
  {'name': 'Carnes', 'image_path': 'assets/images/carne.jpg'},
  {'name': 'Cogumelos', 'image_path': 'assets/images/cogumelos.jpg'},
  {'name': 'Defumados', 'image_path': 'assets/images/defumados.jpg'},
  {'name': 'Derivados de trigo', 'image_path': 'assets/images/trigo.jpg'},
  {'name': 'Derivados de mandioca', 'image_path': 'assets/images/mandioca.jpg'},
  {'name': 'Derivados de cana', 'image_path': 'assets/images/cana.jpg'},
  {'name': 'Desidatrados', 'image_path': 'assets/images/desidratados.jpeg'},
  {'name': 'Doces', 'image_path': 'assets/images/doces.jpg'},
  {'name': 'Flores', 'image_path': 'assets/images/flores.jpg'},
  {'name': 'Frango Caipira', 'image_path': 'assets/images/frango.jpg'},
  {'name': 'Frutas', 'image_path': 'assets/images/frutas.jpeg'},
  {'name': 'Graos', 'image_path': 'assets/images/graos.jpeg'},
  {'name': 'Hortaliças', 'image_path': 'assets/images/hortalicas.jpg'},
  {'name': 'Laticinios', 'image_path': 'assets/images/laticinios.jpg'},
  {'name': 'Legumes', 'image_path': 'assets/images/legumes.jpeg'},
  {'name': 'Ovos de Galinha', 'image_path': 'assets/images/ovos.jpeg'},
  {'name': 'Peixes', 'image_path': 'assets/images/peixe.jpg'},
  {'name': 'Polpa de frutas', 'image_path': 'assets/images/polpa.jpg'},
  {'name': 'Pratos congelados', 'image_path': 'assets/images/congelados.jpg'},
  {'name': 'Sorvetes', 'image_path': 'assets/images/sorvetes.jpeg'},
  {'name': 'Outros', 'image_path': 'assets/images/outros.jpg'},
];
