List<String> announcementsCategories = [
  'Frangos Caipira',
  'Galinhas poedeiras',
  'Ovos de Galinha',
  'Ovos férteis',
  'Licor',
  'Suco',
  'Vinho',
  'Carne suína',
  'Carne Caprina/Ovina',
  'Carne de Frango',
  'Carne de Outras Aves',
  'Peixes',
  'Cogumelos em Conserva',
  'Champingnon',
  'Cogumelo Hiratake',
  'Cogumelo Hiratake Salmão',
  'Cogumelo Shimeji',
  'Mandioca Descascada Congelada',
  'Polpa de frutas',
  'Pratos congelados',
  'Sorvetes',
  'Açucar Mascavo',
  'Melado',
  'Rapadura',
  'Farinha de Mandioca',
  'Farinha de Tapioca',
  'Massa de Tapioca',
  'Massa para Bolos',
  'Hibiscus',
  'Hortaliças',
  'Plantas Aromáticas',
  'Doce de Corte',
  'Doce Pastoso',
  'Agave',
  'Areca bambu',
  'Arnica',
  'Áster',
  'Azaléia',
  'Babosa',
  'Bambu',
  'Begonia - Vaso',
  'Boldo',
  'Bromélias',
  'Buxinho',
  'Cactos/suculentas',
  'Citronela',
  'Cróton',
  'Dracena',
  'Fenix',
  'Ficus - Folhagem',
  'Brinco de princesa',
  'Capuchinha',
  'Geranio comum',
  'Heliconias',
  'Jurubeba',
  'Lavanda',
  'Liriopsis',
  'Margarida',
  'Moréia',
  'Moringa',
  'Mudas Frutíferas',
  'Mudas Nativas',
  'Murta',
  'Orquídeas - Catlleya',
  'Palmeiras em geral',
  'Pata de elefante',
  'Primavera - bouganville',
  'Rosa - Corte',
  'Rosa do deserto',
  'Samambaia americana',
  'Tango',
  'Vinagreira',
  'Abacate',
  'Abacaxi',
  'Acerola',
  'Amora',
  'Banana',
  'Caju',
  'Cará',
  'Carambola',
  'Coco',
  'Figo',
  'Framboesa',
  'Goiaba',
  'Graviola',
  'Jabuticaba',
  'Jaca',
  'Laranja',
  'Limão',
  'Mamão',
  'Manga',
  'Maracujá',
  'Melancia',
  'Morango',
  'Pitaia',
  'Pitanga',
  'Tamarindo',
  'Tangerina',
  'Uva',
  'Amendoim',
  'Arroz',
  'Café',
  'Milho',
  'Soja',
  'Feijão',
  'Abóbora',
  'Açafrão da terra',
  'Acelga',
  'Couve Chinesa',
  'Agrião',
  'Alface',
  'Algodão',
  'Alho',
  'Almeirão',
  'Batata',
  'Batata-doce',
  'Berinjela',
  'Beterraba',
  'Brócolis',
  'Cebola',
  'Cebolinha',
  'Cenoura',
  'Chicória',
  'Chuchu',
  'Coentro',
  'Couve',
  'Couve-flor',
  'Ervilha',
  'Espinafre',
  'Feijão-de-corda',
  'Gengibre',
  'Hibiscus',
  'Hortelã',
  'Inhame',
  'Jiló',
  'Mandioca',
  'Maxixe',
  'Milho-verde',
  'Mostarda',
  'Ora pro nobis',
  'Iogurte',
  'Queijo',
  'Leite',
  'Biscoitos',
  'Bolos',
  'Pães',
  'Salgados',
  'Artesanato',
  'Abelhas',
  'Animais Ornamentais',
  'Composto orgânico Bokashi',
  'Esterco de gado',
  'Café',
  'Cabritas/Cabritos',
  'Damasco',
  'Defumado de Suínos',
  'Farinha de Trigo',
  'Linguiça artesanal e defumados',
  'Potros/Potras',
  'Cana-de-açucar',
  'Feno',
  'Geléias',
  'Pepino',
  'Pimenta',
  'Pimentão',
  'Quiabo',
  'Rabanete',
  'Repolho',
  'Rúcula',
  'Salsa',
  'Tomate',
  'Mel',
  'Extrato de Tomate',
  'Molho de Pimenta',
  'Carneiros',
  'Cordeiros/Cordeiras',
  'Eucalipto',
  'Leitoes/Leitoas',
  'Outros',
];
