List<String> announcementsCategories = [
  'Artesanato',
  'Açucar',
  'Bebidas',
  'Café',
  'Carne bovina',
  'Carne suína',
  'Carne Caprina/Ovina',
  'Carne de Frango',
  'Carne de Outras Aves',
  'Cogumelos',
  'Derivados de Trigo',
  'Desidratados',
  'Doces',
  'Farinha de Mandioca',
  'Farinha de Tapioca',
  'Frango Caipira',
  'Flores',
  'Frutas',
  'Galinhas',
  'Graos',
  'Hortaliças',
  'Iogurte',
  'Leite',
  'Legumes',
  'Massa de Tapioca',
  'Massa para Bolos',
  'Melado',
  'Ovos de Galinha',
  'Ovos férteis',
  'Peixes',
  'Pratos congelados',
  'Polpa de frutas',
  'Sorvetes',
  'Outros',
];
