List<String> announcementsCategories = [
  'Abacate',
  'Abacaxi',
  'Abelhas',
  'Abóbora',
  'Acelga',
  'Acerola',
  'Agave',
  'Agrião',
  'Alface',
  'Algodão',
  'Alho',
  'Almeirão',
  'Amendoim',
  'Amora',
  'Animais Ornamentais',
  'Areca bambu',
  'Arnica',
  'Arroz',
  'Artesanato',
  'Áster',
  'Azaléia',
  'Açafrão da terra',
  'Açúcar Mascavo',
  'Babosa',
  'Bambu',
  'Banana',
  'Batata',
  'Batata-doce',
  'Begônia - Vaso',
  'Berinjela',
  'Beterraba',
  'Biscoitos',
  'Boldo',
  'Bolos',
  'Brinco de princesa',
  'Bromélias',
  'Brócolis',
  'Buxinho',
  'Cabritas/Cabritos',
  'Cactos/suculentas',
  'Café',
  'Café',
  'Caju',
  'Cana-de-açúcar',
  'Capuchinha',
  'Carambola',
  'Carne Caprina/Ovina',
  'Carne de Frango',
  'Carne de Outras Aves',
  'Carne suína',
  'Carneiros',
  'Cará',
  'Cebola',
  'Cebolinha',
  'Cenoura',
  'Champignon',
  'Chicória',
  'Chuchu',
  'Citronela',
  'Coco',
  'Coentro',
  'Cogumelo Hiratake Salmão',
  'Cogumelo Hiratake',
  'Cogumelo Shimeji',
  'Cogumelos em Conserva',
  'Composto orgânico Bokashi',
  'Cordeiros/Cordeiras',
  'Couve Chinesa',
  'Couve',
  'Couve-flor',
  'Cróton',
  'Damasco',
  'Defumado de Suínos',
  'Doce Pastoso',
  'Doce de Corte',
  'Dracena',
  'Ervilha',
  'Espinafre',
  'Esterco de gado',
  'Eucalipto',
  'Extrato de Tomate',
  'Farinha de Mandioca',
  'Farinha de Tapioca',
  'Farinha de Trigo',
  'Feijão',
  'Feijão-de-corda',
  'Fenix',
  'Feno',
  'Ficus - Folhagem',
  'Figo',
  'Framboesa',
  'Frangos Caipira',
  'Galinhas poedeiras',
  'Geléias',
  'Gengibre',
  'Gerânio comum',
  'Goiaba',
  'Graviola',
  'Heliconias',
  'Hibiscus',
  'Hibiscus',
  'Hortaliças',
  'Hortelã',
  'Inhame',
  'Iogurte',
  'Jabuticaba',
  'Jaca',
  'Jiló',
  'Jurubeba',
  'Laranja',
  'Lavanda',
  'Leite',
  'Leitoes/Leitoas',
  'Licor',
  'Limão',
  'Linguiça artesanal e defumados',
  'Liriopsis',
  'Mamão',
  'Mandioca Descascada Congelada',
  'Mandioca',
  'Manga',
  'Maracujá',
  'Margarida',
  'Massa de Tapioca',
  'Massa para Bolos',
  'Maxixe',
  'Mel',
  'Melado',
  'Melancia',
  'Milho',
  'Milho-verde',
  'Molho de Pimenta',
  'Morango',
  'Moringa',
  'Moréia',
  'Mostarda',
  'Mudas Frutíferas',
  'Mudas Nativas',
  'Murta',
  'Ora pro nobis',
  'Orquídeas - Catlleya',
  'Outros',
  'Ovos de Galinha',
  'Ovos férteis',
  'Palmeiras em geral',
  'Pata de elefante',
  'Peixes',
  'Pepino',
  'Pimenta',
  'Pimentão',
  'Pitaia',
  'Pitanga',
  'Plantas Aromáticas',
  'Polpa de frutas',
  'Potros/Potras',
  'Pratos congelados',
  'Primavera - bouganville',
  'Pães',
  'Queijo',
  'Quiabo',
  'Rabanete',
  'Rapadura',
  'Repolho',
  'Rosa - Corte',
  'Rosa do deserto',
  'Rúcula',
  'Salgados',
  'Salsa',
  'Samambaia americana',
  'Soja',
  'Sorvetes',
  'Suco',
  'Tamarindo',
  'Tangerina',
  'Tango',
  'Tomate',
  'Uva',
  'Vinagreira',
  'Vinho',
];
